### PR TITLE
Add some transformers and mtl support

### PR DESCRIPTION
**Pull request by ddssff**
This is some code I wrote to use UnexceptionalIO in monad transformers and monad transformer classes.  It probably belongs in a separate package.

### CODE REVIEW

**Comment by ddssff** [comment]
"liftIO" is a dubious function name choice.

**Comment by singpolyma** [comment]
You may be interested in the unexceptional-trans package

**Comment by ddssff** [comment]
Is there a github repository for unexceptionalio-trans?  The one in the cabal file isn't working.

**Comment by ddssff** [comment]
Do you use this package currently?  Or is it superseded by something else, or did it just not turn out to be used?  I'm asking because it seems to solve an important problem, but it only has a few reverse dependencies.  And unexceptionalio-trans needs a patch.

**Comment by singpolyma-shopify** [comment]
https://github.com/singpolyma/unexceptional-trans

**Comment by singpolyma-shopify** [comment]
I use this package (and usually the -trans package) on most of my Haskell projects, personally

**Comment by ddssff** [comment]
Thanks for the link, I was looking for unexceptionalio-trans, so I missed unexceptional-trans.  By the way, the version uploaded to hackage is missing a Monoid w constraint on the WriterT instance.

**Pull request closed without merging**
